#!/usr/bin/env sh

configure_kbswitch() {
    sleep 1
    echo "configure keyboards"
    setxkbmap -option 'grp:rctrl_rshift_toggle' -layout us,es
}

configure_kbswitch

[[ ! $(command -v bluetoothctl) ]] && exit 0

while :; do

    bluetoothctl | while read -r; do
        if [ "$(systemctl is-active bluetooth)" = "active" ]; then
            bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2 | while read -r line; do
                if bluetoothctl info "$line" | grep -q "Connected: yes"; then
                    configure_kbswitch
                fi
            done
        fi
    done

done
