#!/usr/bin/env bash
#
# https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
# ${THEME/-dark/}
#

dark='Adwaita-dark'
light='Adwaita'
current="$(xfconf-query -c xsettings -p /Net/ThemeName)"

icon_dark='Papirus-Dark'
icon_light='Papirus'

set_gtk_theme() {
    local theme="$1"

    xfconf-query -c xsettings -p /Net/ThemeName -s "$theme"
    gsettings set org.gnome.desktop.interface gtk-theme "$theme"
}

set_gtk_icon_theme() {
    local theme="$1"

    xfconf-query -c xsettings -p /Net/IconThemeName -s "$theme"
    gsettings set org.gnome.desktop.interface icon-theme "$theme"
}

if [[ $current =~ dark ]]; then
    set_gtk_theme "$light"
    set_gtk_icon_theme "$icon_light"
else
    set_gtk_theme "$dark"
    set_gtk_icon_theme "$icon_dark"
fi
