#!/usr/bin/env bash
#
# Color format: rrggbb[aa]
#

# xrescat unsigned
xrc() {
    xrescat "$1" | sed s/^\#//
}

# ---
# Defaults
# ---
display_on=1
span_image=false
lock_timeout=300
fx_list=(blur)
dim_level=40
blur_level=1
pixel_scale=10,1000

# ---
# Theme
# ---
# Login box
loginbox=$(xrc multilock.loginbox.color)
loginshadow=$(xrc multilock.loginbox.color)

# Text
locktext=""
font="monospace"
layoutcolor=00000000

# Ring
ringcolor=$(xrc multilock.ring.color)
ringvercolor=$(xrc multilock.ring.color)
ringwrongcolor=$(xrc multilock.ring.color)
verifcolor=$(xrc multilock.ring.color)

# Key highlight (ring)
separatorcolor=$(xrc multilock.keyhl.separator-color)
keyhlcolor=$(xrc multilock.keyhl.keypressed-color) # key pressed
bshlcolor=$(xrc multilock.keyhl.backspace-color) # backspace pressed

# Circle
insidecolor=$(xrc multilock.circle.inside-color)
insidevercolor=$(xrc multilock.circle.inside-verify-color)
insidewrongcolor=$(xrc multilock.circle.inside-wrong-color)

# Date
timecolor=$(xrc multilock.date.time-color)
datecolor=$(xrc multilock.date.date-color)

# ---
# Tasks
# ---
# Override tasks to empty
prelock() {
    echo "Running prelock..."
}

postlock() {
    echo "Running postlock..."
}
