#!/bin/bash

set -e

# Install homebrew
if ! [ -x "$(command -v brew)" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew tap 'caskroom/cask' \
  'homebrew/cask-versions' \
  'caskroom/fonts' \
  'homebrew/core'

brew install \
  'docker-compose' \
  'mas' \
  'shellcheck' \
  'tree' \
  'tldr' \
  'youtube-dl'

brew cask install \
    'appcleaner' \
    'balenaetcher' \
    'calibre' \
    'contexts' \
    'clover-configurator' \
    'cyberduck' \
    'discord' \
    'docker' \
    'google-backup-and-sync' \
    'google-chrome' \
    'google-chrome-canary' \
    'firefox' \
    'handbrake' \
    'homebrew/cask-fonts/font-roboto-mono' \
    'iina' \
    'iterm2' \
    'jetbrains-toolbox' \
    'keka' \
    'kext-utility' \
    'megasync' \
    'nativedisplaybrightness' \
    'nightowl' \
    'plug' \
    'pocket-casts' \
    'safeincloud-password-manager' \
    'sensiblesidebuttons' \
    'sequel-pro' \
    'sourcetree' \
    'spectacle' \
    'spotify' \
    'slack' \
    'telegram-desktop' \
    'transmission' \
    'typora' \
    'visual-studio-code'

mas install \
    # Numbers
    '409203825' \
    # Pages
    '409201541' \
    # Pixelmator
    '407963104' \
    # Reeder 3
    '880001334' \
    # XMind ZEN
    '1327661892' \
    # XCode
    #'497799835' \
    # Spark Email
    '1176895641' \
    # Pocket
    '568494494' \
    # Tweetbot 3
    '1384080005' \
    # Wunderlist
    '410628904' \
    # Encrypto
    '935235287'
