#!/bin/bash

set -e

# Homebrew
if ! [ -x "$(which brew)" ]; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update

brew tap 'caskroom/cask' \
  'homebrew/cask-versions' \
  'caskroom/fonts' \
  'homebrew/core'

brew install \
  'docker-compose' \
  'mas' \
  'shellcheck' \
  'tree' \
  'tldr'

brew cask install \
    'appcleaner' \
    'calibre' \
    'contexts' \
    'clover-configurator' \
    'cyberduck' \
    'discord' \
    'docker' \
    'google-backup-and-sync' \
    'google-chrome' \
    'google-chrome-canary' \
    'firefox' \
    'homebrew/cask-fonts/font-roboto-mono' \
    'iina' \
    'iterm2' \
    'jetbrains-toolbox' \
    'keka' \
    'megasync' \
    'nativedisplaybrightness' \
    'nightowl' \
    'pocket-casts' \
    'safeincloud-password-manager' \
    'sensiblesidebuttons' \
    'sequel-pro' \
    'sourcetree' \
    'spectacle' \
    'spotify' \
    'slack' \
    'telegram-desktop' \
    'typora' \
    'visual-studio-code'

mas install \
    # Numbers
    '409203825' \
    # Pages
    '409201541' \
    # Pixelmator
    '407963104' \
    # Reeder 3
    '880001334' \
    # XMind ZEN
    '1327661892' \
    # XCode
    '497799835' \
    # Spark Email
    '1176895641' \
    # Pocket
    '568494494' \
    # Tweetbot 3
    '1384080005'
