# general
DOTFILES_PATH="${HOME}/dotfiles"
DOTFILES_SYMLINKS="${DOTFILES_PATH}/symlinks"
DOTFILES_DEFAULT_SYMLINKS="${DOTFILES_SYMLINKS}/config.yaml"

# dependency versions
ZPLUG_VERSION="2.4.2"
DOTMAN_VERSION="0.1.0"

# dependencies
DEPENDENCIES_PATH="${DOTFILES_PATH}/dependencies"
ZPLUG_PATH="${DEPENDENCIES_PATH}/zplug"
DOTMAN_PATH="${DEPENDENCIES_PATH}/dotman"

# zplug
ZPLUG_HOME="${ZPLUG_PATH}/${ZPLUG_VERSION}"

# dotman
DOTMAN_HOME="${DOTMAN_PATH}/${DOTMAN_VERSION}"
DOTMAN_BIN="${DOTMAN_HOME}/dotman"

# vscode
CODE_MAC_SYMLINKS="${DOTFILES_SYMLINKS}/vscode_mac.yaml"

# dot
DOT_PATH="${DOTFILES_PATH}/bin"
DOT_BIN="${DOT_PATH}/dot"
DOT_SCRIPTS_PATH="${DOTFILES_PATH}/scripts"
DOT_SYMLINKS="${DOTFILES_SYMLINKS}/dot.yaml"

# config
DOTFILES_CONFIG=true
