# general
DOTFILES_PATH="${HOME}/dotfiles"
DOTFILES_SYMLINKS="${DOTFILES_PATH}/symlinks"
DOTFILES_DEFAULT_SYMLINKS="${DOTFILES_SYMLINKS}/config.yaml"

# dependency versions
ZPLUG_VERSION="2.4.2"
DOTMAN_VERSION="0.1.0"

# dependencies
DEPENDENCIES_PATH="${DOTFILES_PATH}/deps"

# zplug
ZPLUG_PATH="${DEPENDENCIES_PATH}/zplug-${ZPLUG_VERSION}"
ZPLUG_HOME="$ZPLUG_PATH"

# dotman
DOTMAN_BIN="${DEPENDENCIES_PATH}/dotman-${DOTMAN_VERSION}"

# vscode
CODE_MAC_SYMLINKS="${DOTFILES_SYMLINKS}/vscode_mac.yaml"

# dot
DOT_PATH="${DOTFILES_PATH}/bin"
DOT_BIN="${DOT_PATH}/dot"
DOT_SCRIPTS_PATH="${DOTFILES_PATH}/scripts"
DOT_SYMLINKS="${DOTFILES_SYMLINKS}/dot.yaml"
