#!/bin/bash

set -e

# arguments
USER_COMMAND=$1

# global variables
DOTFILES_DIR="${HOME}/dotfiles"
CLI_DIR="${DOTFILES_DIR}/cli"

# init cli
source "${CLI_DIR}/command.sh"

execute_command "$USER_COMMAND"

exit 0

