#!/usr/bin/env bash

set -e

remote="$1"

if [ "$remote" == "-r" ] || [ "$remote" == "--remote" ]; then
  DOTFILES_PATH="${HOME}/dotfiles"

  if ! [ -d "$DOTFILES_PATH" ]; then
    echo "Cloning dotfiles in ${DOTFILES_PATH}"
    git clone https://github.com/aerz/dotfiles.git "${DOTFILES_PATH}"
  else
    echo "Error: Use remote option only on a fresh installation"
    echo "Remove your dotfiles folder and try again"
    exit 1
  fi

  shift $# # remove all arguments before run the installer
  source "${DOTFILES_PATH}/install"
else
  source "${HOME}/dotfiles/config.sh"
  source "${DOT_SCRIPTS_PATH}/_core/init.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/welcome.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/os_default.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/requirements.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/dependencies.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/symlinks.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/dot.sh"
  source "${DOT_SCRIPTS_PATH}/_core/install/finish.sh"
fi
