#!/usr/bin/env bash

set -euo pipefail

echo ""
echo "Installing dotfiles..."
echo ""

readonly DOTFILES_PATH="${HOME}/dotfiles"

# error if dotfiles already exist
if [ -d "$DOTFILES_PATH" ]; then
  echo "dotfiles folder already exist!"
  echo "delete the folder and run the command again"
  echo ""
  exit 1
fi

# clone the dotfiles
git clone https://github.com/aerz/dotfiles.git "$DOTFILES_PATH"

# dot command alias
sudo ln -sfv "${DOTFILES_PATH}/bin/dot" "/usr/local/bin/dot"

# search the dot alias and show error if it's not exist
if [ -z "$(ls -la /usr/local/bin | grep -w 'dot')" ]; then
  echo ""
  echo "Error: dot command was not installed, try to install it manually..."
  exit 1
fi

echo ""
echo "dotfiles installed successfully"
echo ""
echo "Type 'dot' on your terminal to start using the dotfiles!"
