#!/usr/bin/env bash

# iTerm2
# Change preferences directory iTerm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "${BASE_DIR}/dotfiles"
# Load custom preferences iTerm2
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
