#!/usr/bin/env zsh

set -e

if [[ "$OSTYPE" == "darwin"* ]]; then
  log::header "Creating symlinks..."
  $DOTMAN_BIN --config "${CODE_MAC_SYMLINKS}" --force
fi

while IFS= read -r ext; do
  code --install-extension "$ext"
done < "${DOTFILES_PATH}/vscode/extensions"
