#!/bin/sh

# defaults
alias \
    emacs="emacsclient -c -a 'emacs'" \
    vim='nvim' vimdiff='nvim -d'

# shorthands
alias \
    ..='cd ..' \
    c='clear' \
    cu='checkupdates; paru -Qum' \
    dw='sudo dmesg -L=always' \
    g='git' \
    jxe='journalctl -xe' \
    p='sudo pacman' \
    udm='sudo udevadm monitor'

# colorize
alias \
    diff='diff --color=always' \
    grep='grep --color=auto' \
    ls='eza --icons=always --color=always --group-directories-first' \
    l='ls -lgh' \
    la='ls -lgah' \
    lt='eza --tree' \
    tree='tree -C'

# verbose
alias \
    cp='cp -iv' \
    mv='mv -iv' \
    rm='rm -vI' \
    bc='bc -ql' \
    rsync='rsync -vrPlu' \
    ffmpeg='ffmpeg -hide_banner' \
    df='df -h' \
    free='free -h'

# helpers
alias \
    gpgak="keychain --quiet --nogui --attempts 2" \
    gpgls='gpg --list-secret-keys --keyid-format LONG' \
    keychain='keychain --quiet' \
    ssh='TERM=xterm-256color ssh' \
    sshak="keychain --quiet --inherit any --attempts 2" \
    sshsum='ssh-keygen -l -f'
