#!/bin/sh

#alias sudo="sudo "

# defaults
alias \
    emacs="emacsclient -c -a 'emacs'" \
    vim='nvim' vimdiff='nvim -d'

alias \
    ..='cd ..' \
    c='clear' \
    g='git' \
    diff='diff --color=always' \
    grep='grep --color=auto' \
    ls='eza --icons=always --color=always --group-directories-first' \
    l='ls -lgh' \
    ll='ls -l' \
    la='ls -lgah' \
    lt='eza --tree'

alias \
    p='sudo pacman' \
    cu='checkupdates; paru -Qum' \
    allup='topgrade --disable containers spicetify yadm' \
    jxe='journalctl -xe' \
    udm='sudo udevadm monitor' \
    dw='sudo dmesg -L=always'

# verbose
alias \
    cp='cp -iv' \
    mv='mv -iv' \
    rm='rm -vI' \
    bc='bc -ql' \
    rsync='rsync -vrPlu' \
    ffmpeg='ffmpeg -hide_banner' \
    df='df -h' \
    free='free -h'

# helpers
alias \
    gpgak="keychain --quiet --nogui --attempts 2" \
    gpgls='gpg --list-secret-keys --keyid-format LONG' \
    keychain='keychain --quiet' \
    ssh='TERM=xterm-256color ssh' \
    sshak="keychain --quiet --inherit any --attempts 2" \
    sshsum='ssh-keygen -l -f'
