#!/bin/bash

set -e

if ! [ -x "$(command -v brew)" ]; then
    echo 'Please, install homebrew first...'
    exit 0
fi

brew install 'node'

npm intall -g \
    'eslint' \
    'tslint' \
    'typescript' \
    'pug-lint'
