#!/usr/bin/env bash
# ---
#
# Bluetooth status icon module script.
#
# Dependencies:
#   - xrescat       (https://github.com/aerz/xrescat)
#   - libnotify     (https://archlinux.org/packages/extra/x86_64/libnotify/)
#   - bluez-utils   (https://archlinux.org/packages/extra/x86_64/bluez-utils/)
#
# ---

readonly COLOR_FG_MUTED="$(xrescat polybar.colors.fg-muted)"
readonly COLOR_SECONDARY="$(xrescat polybar.colors.secondary)"

bluetooth_is_on() {
    if [ -z "$(timeout 1 bluetoothctl show | grep 'Powered: no')" ]; then
        echo "yes"
    else
        echo "no"
    fi
}

bluetooth_print() {
    echo "%{F${COLOR_FG_MUTED}}%{F-}"

    bluetoothctl | while read -r; do
        if [ "$(systemctl is-active bluetooth)" == "active" ] && [ "$(bluetooth_is_on)" == "yes" ]; then
            echo ""

            bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2 | while read -r device; do
                if bluetoothctl info "$device" | grep -q "Connected: yes"; then
                    echo "%{F${COLOR_SECONDARY}}%{F-}"
                fi

            done
        else
            echo "%{F${COLOR_FG_MUTED}}%{F-}"
        fi
    done
}

connect_bluetooth_devices() {
    local devices="$1"

    bluetoothctl power on >> /dev/null
    notify-send ' Bluetooth powered on' 'Trying to connect paired devices...'
    sleep .5

    echo "$devices" | while read -r device; do
        bluetoothctl connect "$device" >> /dev/null

        if [ $? -eq 0 ]; then
            notify-send ' Connected' "$(bluetoothctl info $device | grep 'Name:' | cut -d ':' -f 2)"
        fi
    done
}

disconnect_bluetooth_devices() {
    local devices="$1"

    notify-send ' Bluetooth disconnection' 'Disconnecting paired devices...'
    echo "$devices" | while read -r device; do
        bluetoothctl disconnect "$device" >> /dev/null
    done
}

case $1 in
    -c|--connect-paired)
        paired="$(bluetoothctl paired-devices | grep Device | cut -d ' ' -f 2)"
        connect_bluetooth_devices "$paired"
    ;;
    -p|--power-switch)
        case "$(bluetooth_is_on)" in
            yes)    bluetoothctl power off  ;;
            no)     bluetoothctl power on   ;;
        esac
    ;;
    *)
        bluetooth_print
    ;;
esac
