#!/usr/bin/env sh
# ---
#
# Microphone status icon module script.
#
# Source:
#   - https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/pulseaudio-microphone/
#
# Dependencies:
#   - xrescat       (https://github.com/aerz/xrescat)
#   - pulseaudio    (https://archlinux.org/packages/extra/x86_64/pulseaudio/)
#
# ---

is_unmuted() {
    test $(ponymix --input is-muted; echo $?) -eq 1
}

print_status() {
    is_unmuted && echo "%{T2}%{T-}" || echo ''
}

listen() {
    print_status

    LANG=EN; pactl subscribe | while read -r event; do
        if echo "$event" | grep -q "source" || echo "$event" | grep -q "server"; then
            print_status
        fi
    done
}

case "$1" in
    toggle) ponymix --input toggle  ;;
    *)      listen                  ;;
esac
