#!/usr/bin/env sh
# ---
#
# Microphone status icon module script.
#
# Source:
#   - https://github.com/polybar/polybar-scripts/blob/master/polybar-scripts/pulseaudio-microphone/
#
# Dependencies:
#   - xrescat       (https://github.com/aerz/xrescat)
#   - pulseaudio    (https://archlinux.org/packages/extra/x86_64/pulseaudio/)
#
# ---

readonly COLOR_FG_MUTED="$(xrescat polybar.colors.fg-muted)"

is_muted() {
    pacmd list-sources | awk '/\*/,EOF {print}' | awk '/muted/ {print $2; exit}'
}

status() {
  [ "$(is_muted)" = "yes" ] && echo "%{F$COLOR_FG_MUTED}%{T2}%{T-}%{F-}" || echo ""
}

listen() {
    status

    LANG=EN; pactl subscribe | while read -r event; do
        if echo "$event" | grep -q "source" || echo "$event" | grep -q "server"; then
            status
        fi
    done
}

toggle() {
  DEFAULT_SOURCE=$(pacmd list-sources | awk '/\*/,EOF {print $3; exit}')

  if [ "$(is_muted)" = "yes" ]; then
      pacmd set-source-mute "$DEFAULT_SOURCE" 0
  else
      pacmd set-source-mute "$DEFAULT_SOURCE" 1
  fi
}

case "$1" in
    --toggle) toggle ;;
    *)        listen ;;
esac
