#!/usr/bin/env sh

updates=0
seconds=0
wait_before_update=5400

get_total_updates() {
    arch=$(checkupdates 2> /dev/null | wc -l)
    aur=$(paru -Qum 2> /dev/null | wc -l)

    updates=$(( $arch + $aur ))
}

send_notify() {
    notify-send -u normal " Updates available!" "$updates Packages ready to update"
}

no_pkgmgr_running_and_timeout_remaining() {
    test $(pgrep "paru|pacman" &> /dev/null ; echo $?) -eq 1 && \
    test $seconds -ne $wait_before_update
}

while true; do
    seconds=0
    get_total_updates
    [ $updates -gt 10 ] && echo "$updates" || echo ""

    while no_pkgmgr_running_and_timeout_remaining; do
        sleep 1 && ((seconds++))
    done
done
