#!/bin/bash

echo "#!/bin/bash

# Clean dock icons
defaults write com.apple.dock persistent-apps -array

# Dock apps backup
defaults write com.apple.dock persistent-apps -array-add '$(defaults read com.apple.dock persistent-apps)';

# Restart Dock
killall Dock" | \
# Remove parenthesis from defaults array command
sed 's/[()]//g' | \
# Format arrays into array add key
sed $'s/,/ \';\r\rdefaults write com.apple.dock persistent-apps -array-add \'/g' > "backup-dock-apps"

# Execution permissions
chmod +x "backup-dock-apps"