#!/usr/bin/env bash

set -eou pipefail

DOT_LOCAL_PATH="/usr/local/bin"

sudo ln -s "$DOTFILES_PATH/bin/dot" "$DOT_LOCAL_PATH/dot"

if [ -z "$(ls $DOT_LOCAL_PATH | grep -w 'dot')" ]; then
    echo
    echo "Error: dot command was not installed, try to install it manually..."
    echo

    exit 1
fi

echo
echo "dot command installed successfully"
echo
echo "Type 'dot' on your terminal to start using it!"
echo