#!/usr/bin/env bash

set -eou pipefail

DOT_LOCAL_PATH="/usr/local/bin"

source "$DOTFILES_PATH/scripts/dot/utils/install.sh"

install_dot
check_dot_is_installed && if  [ $? -eq 1 ]; then exit 1; fi

echo
echo "dot command installed successfully"
echo
echo "Type 'dot' on your terminal to start using it!"
echo