source "$DOTFILES_PATH/scripts/_core/colors.sh"
source "$DOTFILES_PATH/scripts/_core/log.sh"
source "$DOTFILES_PATH/scripts/_core/utils.sh"
source "$DOTFILES_PATH/scripts/_core/docs.sh"
source "$DOTFILES_PATH/scripts/_core/args.sh"
source "$DOTFILES_PATH/scripts/_core/collection.sh"
