#!/usr/bin/env zsh

set -e

if ! [ -x "$(command -v brew)" ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

log::info "Updating brew"

brew update

brew tap homebrew/core
brew tap homebrew/cask
brew tap homebrew/cask-fonts
brew tap homebrew/cask-versions

log::info "Installing brew apps"

brew install \
  bash \
  docker-compose \
  exa \
  nvm \
  mas \
  moreutils \
  grep \
  ruby \
  shellcheck \
  tldr \
  tree \
  youtube-dl \
  wget

log::info "Installing brew cask apps"

brew cask install \
  appcleaner \
  balenaetcher \
  clover-configurator \
  contexts \
  docker \
  downie \
  firefox \
  firefox-developer-edition \
  font-fira-code \
  google-chrome \
  google-chrome-canary \
  iina \
  iterm2 \
  nativedisplaybrightness \
  notion \
  pocket-casts \
  postman \
  sensiblesidebuttons \
  telegram-desktop \
  visual-studio-code
