#!/usr/bin/env zsh

set -e

if ! check::command_installed "brew" 2>&- ; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

log::info "Installing brew apps..."

brew bundle --file="$DOTFILES_PATH/mac/Brewfile"
