#!/usr/bin/env zsh

set -e

brew update

brew tap homebrew/core
brew tap homebrew/cask
brew tap homebrew/cask-fonts
brew tap homebrew/cask-versions

brew install \
  bash \
  docker-compose \
  exa \
  nvm \
  mas \
  grep \
  ruby \
  shellcheck \
  tldr \
  tree \
  youtube-dl \
  wget

brew cask install \
  appcleaner \
  balenaetcher \
  clover-configurator \
  contexts \
  docker \
  downie \
  firefox \
  firefox-developer-edition \
  font-fira-code \
  google-chrome \
  google-chrome-canary \
  iina \
  iterm2 \
  nativedisplaybrightness \
  notion \
  pocket-casts \
  postman \
  sensiblesidebuttons \
  telegram-desktop \
  visual-studio-code
