#!/usr/bin/env bash

##? Link the iterm2 configuration of this dotfiles
##?
##? Usage:
##?   iterm2
##?
##? Options:
##?   -h --help  Print this help command

log "Setting iterm2 preferences"
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DOTFILES_PATH/mac/iterm2"
log --success "iterm2 preferences"

log "Setting custom preferences"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
log --success "iterm2 custom preferences"
