#!/usr/bin/env zsh

set -e

log::header "Installing apps from Mac App Store"

check::command_installed "mas" -v

mas_apps=(
  1384080005  # Tweetbot 3
  441258766   # Magnet
  497799835   # XCode
)

for app in ${mas_apps[@]};
do
  mas install "$app"
done
