#!/usr/bin/env bash
#
# PulseAudio operations using Rofi as interface
#
# Source:
#   https://gist.github.com/Nervengift/844a597104631c36513c
#
# Dependencies:
#   ponymix
#   pulseaudio
#   rofi
#

# ---

# Rofi options
rofi_opts=(
    "-i"
    "-matching fuzzy"
    "-theme ~/.config/rofi/themes/notifications.rasi"
    "-dmenu"
)

# ---

show_help() {
    echo
    echo "pasound - PulseAudio control using Rofi"
    echo
    echo "usage: pasound [options] <command>"
    echo
    echo "Commands:"
    echo "  help                    Display this message"
    echo "  umute                   Toggle mute on apps playing sound"
    echo "  input                   Set default sound device input"
    echo "  output                  Set default sound device output"
    echo
    echo "Options:"
    echo "  -i, --ignore REGEX      Do not display results found with regex to Rofi"
    exit 0
}

show_cmd_err() {
    echo "error: No command specified"
    echo
    echo "Use 'pasound help' to display the help message"
    exit 1
}

show_no_dev_err() {
    echo "No sound device selected"
    exit 1
}

show_no_app_err() {
    echo "No app selected"
    exit 1
}

show_bad_args_err() {
    echo "error: No options or arguments are allowed after command"
    exit 1
}

open_output_menu() {
    local title="墳 Default Output:"
    local ignore="$1"

    if [ ! -z "$ignore" ]; then
        grep -Pv "$ignore"  | rofi ${rofi_opts[@]} -p "$title"
    else
        rofi ${rofi_opts[@]} -p "$title"
    fi
}

open_input_menu() {
    local title="墳 Toggle mute:"

    rofi ${rofi_opts[@]} -p "$title"
}

list_apps_sound() {
    ponymix -t sink-input list | \
    awk '
        /^sink-input/ {
            sid = $2

            getline
            gsub(/^ +/, "", $0)
            app = $0

            getline
            icon = match($0, /\[Muted\]/) ? "" : ""

            print icon" "sid" "app
        }
    '
}

list_sound_outputs() {
    local default_id="$(
        ponymix defaults | \
        awk '
            /^sink/ {
                id = $2
                print id
            }
        '
    )"

    ponymix -t sink list | \
    awk -v default_id="$default_id" '
        /^sink/ {
            sinkid = $2

            getline
            gsub(/^ +/, "", $0)
            name = $0
            icon = $default_id == $sinkid ? " " : ""

            print output icon sinkid" "name
        }
    '
}

[ -z $1 ] && show_cmd_err

while (( $# > 0 )); do
    arg="$1"

    case $arg in
        -i|--ignore)
            ignore="$2"
            shift 2
        ;;
        umute)
            shift
            [ $# -gt 0 ] && show_bad_args_err

            id=$(list_apps_sound | open_input_menu | grep -Po '([0-9]+)(?=:)')
            [ -z "$id" ] && show_no_app_err

            ponymix --sink-input -d $id toggle
        ;;
        output)
            shift
            [ $# -gt 0 ] && show_bad_args_err

            id=$(list_sound_outputs | open_output_menu "$ignore" | grep -Po '[0-9]+(?=:)')
            [ -z "$id" ] && show_no_dev_err

            ponymix set-default -d $id
        ;;
        help)   show_help           ;;
        *)      show_no_cmd_err     ;;
    esac
done
