#!/usr/bin/env bash
#
# Description:
#   Common sound operations using rofi
#
# Dependencies:
#   ponymix
#   pulseaudio
#   rofi
#
# ---
# Config
# ---
readonly ROFI_OPTS=(
    -i
    -matching fuzzy
    -theme ~/.config/rofi/themes/notifications.rasi
    -dmenu
)

# ---

help_msg() {
    echo "
$0 - Common sound operations using rofi

usage: $0 [options]

Options:
  --help                    Display help message
  --mute                    Toggle program muting
  --input                   Set the default microphone device
  --output                  Set the default sound device
  --ignore <regex>          Do not display matches found by regex"
    exit 0
}

err_no_regex() {
    echo "No regex expression provided in ignore option"
    exit 1
}

err_no_opt_exist() {
    echo "$1 option does not exist. See $0 --help"
    exit 1
}

filter_id_selection() {
    grep -Po '([0-9]+)(?=:)'
}

menu_output_devices() {
    local title="墳 Default Output"
    local ignore_arg="$1"
    
    if [ -n "$ignore_arg" ]; then
        grep -Pv "$ignore_arg" | rofi "${ROFI_OPTS[@]}" -p "$title"
    else
        rofi "${ROFI_OPTS[@]}" -p "$title"
    fi
}

menu_mute_programs() {
    local title="墳 Toggle mute"

    rofi "${ROFI_OPTS[@]}" -p "$title"
}

menu_input_devices() {
    local title=" Default Microphone"
    local ignore_arg="$1"

    if [ -n "$ignore_opt" ]; then
        grep -Pv "$ignore_arg" | rofi "${ROFI_OPTS[@]}" -p "$title"
    else
        rofi "${ROFI_OPTS[@]}" -p "$title"
    fi
}

list_apps_sound() {
    ponymix -t sink-input list | awk '
        /^sink-input/ {
            sid = $2

            getline
            gsub(/^ +/, "", $0)
            app = $0

            getline
            icon = match($0, /\[Muted\]/) ? "" : ""

            print icon" "sid" "app
        }'
}

list_input_devices() {
    local default_id
    default_id="$(ponymix --short | awk '/^source/ { print $2 }')"
    
    ponymix --input list | awk -v default_id="$default_id" '
        /input/ {
            gsub(/:/, "", $2)
            id = $2

            getline
            gsub(/^ +/, "", $0)
            name = $0
            icon = (default_id == id) ? " " : ""

            print icon id": "name
        }'
}

list_sound_outputs() {
    local default_id
    default_id="$(ponymix defaults | awk '
        /^sink/ {
            gsub(/:/, "", $2)
            id = $2
            print id
        }')"

    ponymix -t sink list | awk -v default_id="$default_id" '
        /^sink/ {
            gsub(/:/, "", $2)
            id = $2

            getline
            gsub(/^ +/, "", $0)
            name = $0
            icon = (default_id == id) ? " " : ""

            print icon id": "name
        }'
}

while (( $# > 0 )); do
    arg="$1"

    case $arg in
        --ignore)
            [ -z "$2" ] && err_no_regex
            ignore_arg="$2" && shift 2
        ;;
        --mute)     shift && cmd_arg="mute"     ;;
        --input)    shift && cmd_arg="input"    ;;
        --output)   shift && cmd_arg="output"   ;;
        --help)     help_msg                    ;;
        *)          err_no_opt_exist "$1"       ;;
    esac
done

case "$cmd_arg" in
    mute)
        id=$(list_apps_sound | menu_mute_programs | filter_id_selection)
        [ -z "$id" ] && exit 0

        ponymix --sink-input -d "$id" toggle
    ;;
    input)
        id=$(list_input_devices | menu_input_devices "$ignore_arg" | filter_id_selection)
        [ -z "$id" ] && exit 0

        ponymix --input -d "$id" set-default
    ;;
    output)
        id=$(list_sound_outputs | menu_output_devices "$ignore_arg" | filter_id_selection)
        [ -z "$id" ] && exit 0

        ponymix set-default -d "$id"
    ;;
    *)
        ./"$0" --output
    ;;
esac
