#!/usr/bin/env bash

# rofi
theme="~/.config/rofi/themes/power.rasi"
uptime="Uptime: $(uptime -p | sed -e 's/up //g')"

declare -a actions=(
    "  Shutdown"
    "  Reboot"
    "  Lock"
    "  Suspend"
    "  Logout"
)

confirm() {
    local yes=""
    local no=""

    [ "$(echo -e "$no\n$yes" | rofi -theme $theme -i -dmenu -lines 2 -p "Confirm")" == "$yes" ]
}

logout_session() {
    i3-msg exit
    loginctl terminate-session "$(cat /proc/self/sessionid)"
}

save_brightness() {
    light -O
}

action="$(printf '%s\n' "${actions[@]}" | rofi -theme $theme -dmenu -l 5 -p "$uptime")"

# exit when action is empty
[ -z "$action" ] && exit 0

case $action in
    *Shutdown) confirm && save_brightness && systemctl poweroff     ;;
    *Reboot)   confirm && save_brightness && systemctl reboot       ;;
    *Lock)     loginctl lock-session                                ;;
    *Suspend)  confirm && systemctl suspend                         ;;
    *Logout)   confirm && logout_session                            ;;
esac
