#!/usr/bin/env bash
#
# Theme mode switcher menu
#
# Config
readonly GTK_LIGHT='Adwaita'
readonly GTK_DARK='Adwaita-dark'
readonly ICON_LIGHT='Papirus'
readonly ICON_DARK='Papirus-Dark'

# ---

set_gtk_theme() {
    local gtk_theme color

    case $1 in
        *Dark)   gtk_theme="$GTK_DARK" color="prefer-dark"   ;;
        *Light)  gtk_theme="$GTK_LIGHT" color="prefer-light" ;;
    esac

    # distro specific
    xfconf-query -c xsettings -p /Net/ThemeName -s "$gtk_theme"
    gsettings set org.gnome.desktop.interface gtk-theme "$gtk_theme"

    # xdg-desktop-portal-gtk
    gsettings set org.gnome.desktop.interface color-scheme "$color"
    gsettings set org.freedesktop.appearance color-scheme "$color"
}

set_gtk_icon_theme() {
    local icon_theme

    case $1 in
        *Dark)   icon_theme="$ICON_DARK"   ;;
        *Light)  icon_theme="$ICON_LIGHT"  ;;
    esac

    xfconf-query -c xsettings -p /Net/IconThemeName -s "$icon_theme"
    gsettings set org.gnome.desktop.interface icon-theme "$icon_theme"
}

open_light_menu() {
    rofi -i -matching fuzzy -theme ~/.config/rofi/themes/theme-mode/light.rasi -lines 2 -dmenu -p 'Change Mode'
}

open_dark_menu() {
    rofi -i -matching fuzzy -theme ~/.config/rofi/themes/theme-mode/dark.rasi -lines 2 -dmenu -p 'Change Mode'
}

gtkc="$(xfconf-query -c xsettings -p /Net/ThemeName)"

case "$gtkc" in
    "$GTK_DARK")   sel=$(printf "%s\n%s" "  Light" "  Dark" | open_dark_menu)   ;;
    "$GTK_LIGHT")  sel=$(printf "%s\n%s" "  Dark" "  Light" | open_light_menu)  ;;
esac

[ -z "$sel" ] && exit 1

set_gtk_theme "$sel"
set_gtk_icon_theme "$sel"
