#!/bin/sh

# ---
# Start XSettings Daemon
# ---
xfsettingsd --replace --daemon

# ---
# Systemd bus import environments
# ---
# Source: /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
#
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# ---
# Xresources
# ---
[ -f "$XRESOURCES" ] && xrdb -merge -I"$HOME" "$XRESOURCES"
[ -f "${XRESOURCES}.$(hostname)" ] && xrdb -merge -I"$HOME" "${XRESOURCES}.$(hostname)"

# ---
# Environment
# ---
export QT_QPA_PLATFORMTHEME='gnome'

# Unused
#export PATH="$PATH:$HOME/.local/bin"
#export GTK_THEME=":dark"
#export QT_STYLE_OVERRIDE="Adwaita-Dark"

# ---
# X Preferences
# ---
# Monitor
standby=600; suspend=600; off=600
xset dpms $standby $suspend $off &

# Lockscreen
inactivity=600; force_bg=180
xset s $inactivity $force_bg s blank s noexpose &
xss-lock -l -- multilockscreen --lock blur &

# ---
# Start i3
# ---
i3cfg="$XDG_CONFIG_HOME/i3/config"

touch "$i3cfg.md5"

if ! md5sum --quiet --check "$i3cfg.md5"; then
    md5sum "$i3cfg.base" "$i3cfg.$(hostname)" > "$i3cfg.md5"
    cat "$i3cfg.base" "$i3cfg.$(hostname)" > "$i3cfg.out"
fi

exec i3 -c "$i3cfg.out"
