#!/bin/sh

# ---
# XFCE Settings Daemon
# ---
xfsettingsd --replace --daemon

# ---
# Systemd bus import environments
# ---
. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
systemctl --user import-environment PATH

# ---
# Load Xresources
# ---
[[ -f $XRESOURCES ]] && xrdb -merge -I$HOME $XRESOURCES

# ---
# Session Env Variables
# ---
export QT_QPA_PLATFORMTHEME='gnome'
export MOZ_USE_XINPUT2=1
#export PATH="$PATH:$HOME/.local/bin"
#export GTK_THEME=":dark"
#export QT_STYLE_OVERRIDE="Adwaita-Dark"

# ---
# GNOME Keyring
# ---
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# ---
# X Preferences
# ---
xss-lock --transfer-sleep-lock -- betterlockscreen --lock blur &

# Disable screensaver and dpms
xset s off -dpms

# Idle actions
xidlehook \
    --detect-sleep --not-when-audio --not-when-fullscreen \
    --socket /tmp/xidlehook.sock \
    --timer 300 'brillo -O && brillo -u 800000 -S 10' 'brillo -u 100000 -I' \
    --timer 10 'loginctl lock-session' 'brillo -u 100000 -I' \
    --timer 60 'systemctl suspend' 'brillo -u 100000 -I' &

# ---
# Start i3
# ---
exec i3
