#!/bin/sh

# ---
# Start XSettings Daemon
# ---
xfsettingsd --replace --daemon

# ---
# Systemd bus import environments
# ---
# Source: /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
#
systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
fi

# ---
# Load Xresources
# ---
[[ -f $XRESOURCES ]] && xrdb -merge -I$HOME $XRESOURCES

# ---
# Session env vars
# ---
export QT_QPA_PLATFORMTHEME='gnome'

# Unused
#export PATH="$PATH:$HOME/.local/bin"
#export GTK_THEME=":dark"
#export QT_STYLE_OVERRIDE="Adwaita-Dark"

# ---
# X Preferences
# ---
# Monitor
standby=300; suspend=300; off=300
xset dpms $standby $suspend $off &

# Lockscreen
inactivity=300; refresh=60
xset s $inactivity $refresh s blank s noexpose &
xss-lock -l -- multilockscreen --lock blur &

# Idle actions
xidlehook --detect-sleep --not-when-audio --not-when-fullscreen \
    --timer 180 \
        'light -O && light -S 5' 'light -I' \
    --timer 180 \
        'systemctl suspend' 'light -I' &

# ---
# Start i3
# ---
exec i3
