#!/usr/bin/env zsh

# run zplug
export ZPLUG_HOME="$HOME/.zplug"
source $ZPLUG_HOME/init.zsh

# theme
zplug "geometry-zsh/geometry"

# zsh enhacements
zplug "junegunn/fzf-bin", \
    as:command, \
    from:gh-r, \
    rename-to:"fzf", \
    frozen:1
zplug "junegunn/fzf", use:"shell/*.zsh"
zplug "Aloxaf/fzf-tab", use:"fzf-tab.zsh"
zplug "zsh-users/zsh-syntax-highlighting", \
    defer:2
zplug "zsh-users/zsh-autosuggestions"

# commands
zplug "agkozak/zsh-z"
zplug "b4b4r07/enhancd", use:init.sh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
