#!/usr/bin/env bash

readonly ROFI_THEME=~/.config/rofi/themes/power.rasi
export ROFI_BG="#292B2B"
export ROFI_FG="#C5C8C6"
export ROFI_SEL_BG="#5C5E5E"
export ROFI_PROMPT_BG="#F0C674"

confirm() {
    local yes="Yes"
    local no="No"

    [[ "$(echo -e "$no\n$yes" |
        rofi -dmenu -i -l 2 -p "Confirm:" -theme $ROFI_THEME)" == "$yes" ]]
}

logout() {
    swaymsg exit
    loginctl terminate-session "$(cat /proc/self/sessionid)"
}

select_action() {
    declare -ar actions=(
        "󰤆  Shutdown"
        "󰜉  Reboot"
        "󰍁  Lock"
        "󰒲  Suspend"
        "󰁯  Hibernate"
        "󰗽  Logout"
    )
    uptime="$(uptime -p | \
        sed 's/up //g;s/ days/d/g;s/ hours/h/g;s/ minutes/m/g;s/ seconds//g;
             s/, //g')"
    theme=$(mktemp)
    sed "s/==uptime==/Uptime ${uptime}/g" $ROFI_THEME > "$theme"

    printf '%s\n' "${actions[@]}" | rofi \
        -dmenu -i -l ${#actions[@]} -p "Power:" -theme "$theme"
}

action="$(select_action)"

# no action selected
[ -z "$action" ] && exit 0

case $action in
    *Shutdown) confirm && systemctl poweroff   ;;
    *Reboot) confirm && systemctl reboot       ;;
    *Lock) loginctl lock-session               ;;
    *Suspend) confirm && systemctl suspend     ;;
    *Hibernate) confirm && systemctl hibernate ;;
    *Logout) confirm && logout                 ;;
esac
