#!/usr/bin/env bash

readonly ROFI_THEME=~/.config/rofi/themes/popup.rasi

light_menu() {
    ROFI_BG="#E3E3E3" \
    ROFI_FG="#262626" \
    ROFI_SEL_BG="#C1C1C1" \
    ROFI_PROMPT_BG="#EDEDED" \
    rofi -dmenu -theme $ROFI_THEME \
        -l 2 -p 'Theme mode'
}

dark_menu() {
    ROFI_BG="#1C1C1C" \
    ROFI_FG="#D9D9D9" \
    ROFI_SEL_BG="#3E3E3E" \
    ROFI_PROMPT_BG="#121212" \
    ROFI_PROMPT_FG="#C5C8C6" \
    rofi -dmenu -theme $ROFI_THEME \
        -l 2 -p 'Theme mode'
}

case "$(darkman get)" in
    dark)   sel=$(printf "%s\n%s" "  Light" "  Dark" | dark_menu)   ;;
    light)  sel=$(printf "%s\n%s" "  Dark" "  Light" | light_menu)  ;;
esac

[ -z "$sel" ] && exit 0

case "$sel" in
    *Dark)  darkman set dark  ;;
    *Light) darkman set light ;;
esac
